WIP: 178
raccoongang/xblock-video pull request #414
Opened 2020-10-15 16:12 UTC by sendr

2020-10-18 09:10 UTC, idegtiarov requested changes
One micro nit inline please take a look.

Did we have a demo and which part is unique? I believe we reuse the same approach from the different xblock is that correct?

2020-10-18 09:10 UTC, idegtiarov commented on video_xblock/video_xblock.py
> +        Returns the Javascript translation file for the currently selected language, if any found by
Please split the title and body of multiple doc-strings by the empty line and control doc-strings are limited by 80 characters.

2020-10-20 08:38 UTC, cmltaWt0 approved these changes

2020-10-20 18:48 UTC, idegtiarov approved these changes

2020-10-20 19:26 UTC, merged